title:              HiFiStreamer
email:              
description:        An Audiophile network streamer built with Linux JeOS
author:             Oren Sokoler
baseurl:            "/"
url:                "https://orenskl.github.io"

# Social Profiles
#twitter_username:   
github_username:    orenskl/HiFiStreamer
#facebook_username:  
#instagram_username:  
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-73DMCELVM8 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
